server:
   port: 8855
   servlet:
     context-path: /happy
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=happymarket
    username: postgres
    password: postgres
  jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
jwt:
  secret: tg5g98h45g98h45g9845hg98hf9834hf9834hjheriheriuher9g8h384y5934yhhtertg
